name: sheet_localization_generator
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  http: ^0.12.0
  meta: ^1.1.7
  csv: ^4.0.3
  recase: ^3.0.0
  code_builder: ^3.2.0
  dart_style: ^1.2.7
  source_gen: ^0.9.0
  flutter_sheet_localization: ^1.0.0
  build: ^1.2.0
  analyzer: ">=0.40.0 <2.0.0"
  collection: ^1.14.11
  intl: ^0.16.1

dev_dependencies:
  build_test: ^0.10.3
  build_runner: ^1.10.4
